### ISSUE TITLE
Coin a name for the concept

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-digital-map-concept#11]
Pick one name from the list

(1) Digital map
(2) Topology map
(3) Multi-layer topology map
(4) Multi-layer network map
(5) Network map
(6) Trust the authors to make the right choice

**Comment by OlgaHuawei** [comment]
Agreed to use the term Service & Infrastructure Maps (SIMAP) at IETF121. The draft has been renamed and updated
